version: '3.8'

services:
  mysql:
    image: mysql:8.0.33-debian
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
